Add active storage
sumon766/backend-doctor-appointment pull request #17
Opened 2023-08-29 17:16 UTC by Elhambasir

## What is done in this PR?
In this PR, I installed active storage to handle image uploading. In order to make the project work with active storage I changed something in the doctor model. For example, I removed the photo column because we have it in the active storage table and no need to have it in the doctor table.

2023-08-29 18:39 UTC, Lul-Abdifan requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @Elhambasir  :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Great work on adding the Add Doctor functionality 👍


#### Changes Required
✔️ Linters are not passing
✔️ See below for other changes

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 18:39 UTC, Lul-Abdifan commented on app/controllers/api/v1/doctors_controller.rb
> +    render json: @doctors.map { |doctor| doctor.as_json.merge({ photo_url: url_for(doctor.photo) }) }
- Could you please look at the screenshot attached below .The form data is not being added to the database.

![Screenshot from 2023-08-29 14-36-49](https://github.com/sumon766/backend-doctor-appointment/assets/86189460/5203d873-82b3-4bd9-97b1-a28f34153f1d)

2023-08-29 18:39 UTC, Lul-Abdifan commented on app/models/doctor.rb
>    validates :name, presence: true
- Please kindly make this code on one line

2023-08-30 09:47 UTC, sumon766 approved these changes
💐 Hi @Elhambasir, 💐

You have done a great job implementing the requirements for the project 🎉. Your project is complete, there is nothing else to say, other than it's time to merge it. Congratulations...🥳👏

![giphy](https://github.com/sumon766/backend-doctor-appointment/assets/22003499/40fe76a0-5366-4eb2-9189-7d520a09888e)

2023-08-30 09:47 UTC, merged